from color import Color

PLAYERS_LOWER_LIMIT = 2
PLAYERS_UPPER_LIMIT = 6
INITIAL_AMOUNT_OF_CARDS_PER_PLAYER = 3
AMOUNT_OF_CHANGE_COLOR_CARDS = 4
AMOUNT_OF_STOP_CARDS = 4
CARD_MAX_NUMERIC_VALUE = 10
CARD_MIN_NUMERIC_VALUE = 1
COLORS = [color for color in Color]
